[package]
name = "databend-common-users"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
io-uring = ["databend-common-meta-store/io-uring"]

[dependencies]
async-backtrace = { workspace = true }
base64 = "0.21"
chrono = { workspace = true }
cidr = { version = "0.2.2" }
databend-common-ast = { workspace = true }
databend-common-base = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-grpc = { workspace = true }
databend-common-management = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-store = { workspace = true }
databend-common-meta-types = { workspace = true }
enumflags2 = { workspace = true }
itertools = "0.13.0"
jwt-simple = { workspace = true }
log = { workspace = true }
p256 = "0.13"
parking_lot = { workspace = true }
passwords = { version = "3.1.16", features = ["common-password"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
databend-common-expression = { workspace = true }
pretty_assertions = "1.3.0"
wiremock = "0.5.14"

[lints]
workspace = true
