[package]
name = "databend-query"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = ["simd"]
simd = ["databend-common-arrow/simd"]
python-udf = ["arrow-udf-python"]
disable_initial_exec_tls = ["databend-common-base/disable_initial_exec_tls"]

memory-profiling = ["databend-common-base/memory-profiling", "databend-common-http/memory-profiling"]
storage-hdfs = ["opendal/services-hdfs", "databend-common-storage/storage-hdfs"]
io-uring = [
    # "databend-common-meta-embedded/io-uring",
    "databend-common-meta-store/io-uring",
    # "databend-common-meta-sled-store/io-uring",
    # "databend-common-meta-raft-store/io-uring",
]

enable_queries_executor = []

[dependencies]
arrow-array = { workspace = true }
arrow-flight = { workspace = true }
arrow-ipc = { workspace = true }
arrow-schema = { workspace = true }
arrow-udf-js = { workspace = true }
arrow-udf-python = { workspace = true, optional = true }
arrow-udf-wasm = { workspace = true }
async-backtrace = { workspace = true }
async-channel = "1.7.1"
async-recursion = "1.1.1"
async-stream = "0.3.3"
async-trait = { workspace = true }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
backon = "0.4"
base64 = "0.21.0"
bumpalo = { workspace = true }
byte-unit = "4.0.19"
byteorder = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
config = { version = "0.13.4", features = [] }
ctor = { workspace = true }
dashmap = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-ast = { workspace = true }
databend-common-base = { workspace = true }
databend-common-cache = { workspace = true }
databend-common-catalog = { workspace = true }
databend-common-cloud-control = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-formats = { workspace = true }
databend-common-functions = { workspace = true }
databend-common-grpc = { workspace = true }
databend-common-hashtable = { workspace = true }
databend-common-http = { workspace = true }
databend-common-io = { workspace = true }
databend-common-license = { workspace = true }
databend-common-management = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-embedded = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-store = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-metrics = { workspace = true }
databend-common-openai = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-pipeline-sinks = { workspace = true }
databend-common-pipeline-sources = { workspace = true }
databend-common-pipeline-transforms = { workspace = true }
databend-common-script = { workspace = true }
databend-common-settings = { workspace = true }
databend-common-sql = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-storages-delta = { workspace = true }
databend-common-storages-factory = { workspace = true }
databend-common-storages-fuse = { workspace = true }
databend-common-storages-hive = { workspace = true }
databend-common-storages-iceberg = { workspace = true }
databend-common-storages-information-schema = { workspace = true }
databend-common-storages-memory = { workspace = true }
databend-common-storages-null = { workspace = true }
databend-common-storages-orc = { workspace = true }
databend-common-storages-parquet = { workspace = true }
databend-common-storages-result-cache = { workspace = true }
databend-common-storages-stage = { workspace = true }
databend-common-storages-stream = { workspace = true }
databend-common-storages-system = { workspace = true }
databend-common-storages-view = { workspace = true }
databend-common-tracing = { workspace = true }
databend-common-users = { workspace = true }
databend-enterprise-aggregating-index = { workspace = true }
databend-enterprise-attach-table = { workspace = true }
databend-enterprise-background-service = { workspace = true }
databend-enterprise-data-mask-feature = { workspace = true }
databend-enterprise-inverted-index = { workspace = true }
databend-enterprise-stream-handler = { workspace = true }
databend-enterprise-vacuum-handler = { workspace = true }
databend-enterprise-virtual-column = { workspace = true }
databend-storages-common-blocks = { workspace = true }
databend-storages-common-cache = { workspace = true }
databend-storages-common-index = { workspace = true }
databend-storages-common-io = { workspace = true }
databend-storages-common-session = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
derive-visitor = { workspace = true }
ethnum = { workspace = true }
fastrace = { workspace = true }
flatbuffers = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
headers = "0.4.0"
hex = "0.4.3"
highway = "1.1"
http = { workspace = true }
humantime = "2.1.0"
indicatif = "0.17.5"
itertools = { workspace = true }
jsonb = { workspace = true }
jwt-simple = { workspace = true }
log = { workspace = true }
lz4 = "1.24.0"
match-template = { workspace = true }
md-5 = "0.10.5"
naive-cityhash = "0.2.0"
num_cpus = "1.16.0"
once_cell = { workspace = true }
opendal = { workspace = true }
opensrv-mysql = { version = "0.7.0", features = ["tls"] }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }
paste = { workspace = true }
petgraph = { version = "0.6.2", features = ["serde-1"] }
pin-project-lite = "0.2.9"
poem = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
recursive = "0.1.1"
regex = { workspace = true }
reqwest = { workspace = true }
rustls = "0.23.17"
rustls-pemfile = "2"
rustls-pki-types = "1"
rustyline = "14"
serde = { workspace = true }
serde_json = { workspace = true }
serde_stacker = { workspace = true }
serde_urlencoded = "0.7.1"
sha2 = { workspace = true }
socket2 = "0.5.3"
sqlx = { version = "0.8", features = ["mysql", "runtime-tokio"] }
strength_reduce = "0.2.4"
sysinfo = "0.30"
tempfile = "3.4.0"
time = "0.3.14"
tokio = { workspace = true }
tokio-stream = { workspace = true, features = ["net"] }
toml = { version = "0.8", default-features = false }
tonic = { workspace = true }
typetag = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }
xorf = { version = "0.11.0", default-features = false, features = ["binary-fuse"] }
[dev-dependencies]
arrow-cast = { workspace = true }
criterion = { workspace = true }
goldenfile = "1.4"
hex = "0.4.3"
jwt-simple = { workspace = true }
maplit = "1.0.2"
mysql_async = { workspace = true }
num = "0.4.0"
ordered-float = { workspace = true }
p256 = "0.13"
pretty_assertions = "1.3.0"
reqwest = { workspace = true }
rmp-serde = "1.1.1"
temp-env = "0.3.0"
tempfile = "3.4.0"
tower = "0.4.13"
url = "2.3.1"
wiremock = "0.6"

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["match-template", "md-5"]
